/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.controller.IngredientController;
import com.controller.RecIngredientsController;
import com.modle.IngredientModle;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javax.swing.JComboBox;
import com.modle.ComboboxModule;
import com.modle.RecipeModule;
import com.controller.RecipeController;
import com.modle.RecIngredientsModle;

/**
 *
 * @author janaka
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form CalculateIngredientsView
     */
    DefaultTableModel ingreDefTablModle;
    DefaultTableModel recDefaultTableModel;
    DefaultTableModel recIngredientsTableModle;
    DefaultTableModel recDetailsEditIngreModle;
    DefaultTableModel recDetailsEditNotIncluModle;
    String selectedIngreName, selectedIngreCategory = null;
    String searchIngreName, searchIngreCategory = null;
    String unitsArray[] = {"teaspoon", "tablespoon", "fluid ounce", "gill", "cup", "pint", "quart", "gallon", "ml", "l", "pound", "ounce", "mg", "g", "kg"};
    ArrayList<RecIngredientsModle> recIngreList = null;

    public HomeView() {

        initComponents();
        ingreDefTablModle = (DefaultTableModel) tableIngreSearch.getModel();
        recDefaultTableModel = (DefaultTableModel) tableRecSearch.getModel();
        recIngredientsTableModle = (DefaultTableModel) tableRecIngredients.getModel();
        recDetailsEditIngreModle = (DefaultTableModel) tableRecEditDetailsSelectedIngre.getModel();
        recDetailsEditNotIncluModle = (DefaultTableModel) tableRecDetailsNotIncluIngre.getModel();
        txtIngreEditId.setEnabled(false);
        txtIngreEditName.setEnabled(false);
        txtIngreEditCategory.setEnabled(false);
        btnIngreEditSetDefult.setEnabled(false);
        btnIngreEditOk.setEnabled(false);
        txtIngreAddName.requestFocus();

        addItemsToCombobox(comboRecCreateUnit, unitsArray);
    }

    private boolean addItemsToCombobox(JComboBox comboxName, String array[]) {
        ComboboxModule com;
        comboxName.removeAllItems();
        for (int i = 0; i < array.length; i++) {
            //System.out.println("array [i]"+array[i]);
            comboxName.addItem(array[i]);
        }
        //System.out.println("combo 0 : "+comboxName.getItemAt(0));
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        panelRecEdit = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnIngerAddCreate = new javax.swing.JButton();
        txtIngreAddName = new javax.swing.JTextField();
        txtIngreAddCategory = new javax.swing.JTextField();
        txtIngreSearchName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIngerAddClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIngreSearchCategory = new javax.swing.JTextField();
        btnIngreSearchFind = new javax.swing.JButton();
        btnIngreSearchClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIngreSearch = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtIngreEditName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIngreEditCategory = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIngreEditId = new javax.swing.JTextField();
        radioIngreEdit = new javax.swing.JRadioButton();
        radioIngreDelete = new javax.swing.JRadioButton();
        btnIngreEditOk = new javax.swing.JButton();
        btnIngreEditSetDefult = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRecCreateName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRecCreateCategory = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRecCreateqty = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        comboRecCreateUnit = new javax.swing.JComboBox();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        btnRecCreateAdd = new javax.swing.JButton();
        btnRecCreateClear = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtRepSearchName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtRecSearchCate = new javax.swing.JTextField();
        btnRepSearchFind = new javax.swing.JButton();
        btnRecSearchClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRecSearch = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtRecEditId = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtRecEditName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtRecEditCate = new javax.swing.JTextField();
        radioRecDelete = new javax.swing.JRadioButton();
        radioRecEdit = new javax.swing.JRadioButton();
        btnRecEditOk = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableRecIngredients = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtRecEditDetailsId = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtRecEditDetailsName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtRecEditDetailsQty = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtRecEditDetailsUnit = new javax.swing.JTextField();
        btnRecEditDetailsOk = new javax.swing.JButton();
        btnRecEditDetailsReset1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtRecEditDetailsSearchName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtRecEditDetailsSearchCate = new javax.swing.JTextField();
        btnRecEditDetailsSearchFind = new javax.swing.JButton();
        btnRecEditDetailsSearchClear = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableRecEditDetailsSelectedIngre = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        txtRecEditDetailsCate = new javax.swing.JTextField();
        btnRecEditDetailsSearchAddToList = new javax.swing.JButton();
        btnRecEditDetailsSave = new javax.swing.JButton();
        btnRecEditReset2 = new javax.swing.JButton();
        btnRecEditDetailsCancel = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableRecDetailsNotIncluIngre = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("ADD New Ingredients ");

        btnIngerAddCreate.setText("ADD");
        btnIngerAddCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngerAddCreateActionPerformed(evt);
            }
        });

        txtIngreAddName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngreAddNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Category");

        btnIngerAddClear.setText("Clear");
        btnIngerAddClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngerAddClearActionPerformed(evt);
            }
        });

        jLabel4.setText("Search Ingredients ");

        jLabel5.setText("Name");

        jLabel6.setText("Category");

        btnIngreSearchFind.setText("Search");
        btnIngreSearchFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreSearchFindActionPerformed(evt);
            }
        });

        btnIngreSearchClear.setText("Clear");
        btnIngreSearchClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreSearchClearActionPerformed(evt);
            }
        });

        tableIngreSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingre ID", "Name", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableIngreSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableIngreSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableIngreSearchKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableIngreSearch);

        jLabel7.setText("Name");

        txtIngreEditName.setEditable(false);

        jLabel8.setText("Category");

        txtIngreEditCategory.setEditable(false);

        jLabel9.setText("Ingre ID");

        txtIngreEditId.setEditable(false);
        txtIngreEditId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngreEditIdActionPerformed(evt);
            }
        });

        radioIngreEdit.setText("Edit");
        radioIngreEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIngreEditActionPerformed(evt);
            }
        });

        radioIngreDelete.setText("Delete");
        radioIngreDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIngreDeleteActionPerformed(evt);
            }
        });

        btnIngreEditOk.setText("OK");
        btnIngreEditOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreEditOkActionPerformed(evt);
            }
        });

        btnIngreEditSetDefult.setText("Set Default");
        btnIngreEditSetDefult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreEditSetDefultActionPerformed(evt);
            }
        });

        jLabel10.setText("Edit / Delete");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnIngreEditSetDefult)
                        .addGap(30, 30, 30)
                        .addComponent(btnIngreEditOk))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radioIngreEdit)
                        .addGap(18, 18, 18)
                        .addComponent(radioIngreDelete))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIngreEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIngreEditCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIngreAddName, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIngreAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIngreEditId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addContainerGap())))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIngreSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtIngreSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(btnIngreSearchClear)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnIngreSearchFind))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(btnIngerAddClear)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnIngerAddCreate))
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIngreAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtIngreAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngerAddCreate)
                    .addComponent(btnIngerAddClear))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIngreSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtIngreSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngreSearchFind)
                    .addComponent(btnIngreSearchClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIngreEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngreEditCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtIngreEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioIngreDelete)
                    .addComponent(radioIngreEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngreEditOk)
                    .addComponent(btnIngreEditSetDefult))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        panelRecEdit.addTab("Ingredients", jPanel5);

        jLabel11.setText("Create Recipe");

        jLabel12.setText("Name");

        txtRecCreateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecCreateNameActionPerformed(evt);
            }
        });

        jLabel13.setText("Category");

        jLabel14.setText("Quantity");

        jLabel15.setText("Unit");

        comboRecCreateUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Search Recipe");

        btnRecCreateAdd.setText("Create");
        btnRecCreateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecCreateAddActionPerformed(evt);
            }
        });

        btnRecCreateClear.setText("Clear");
        btnRecCreateClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecCreateClearActionPerformed(evt);
            }
        });

        jLabel17.setText("Name");

        jLabel18.setText("Category");

        txtRecSearchCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecSearchCateActionPerformed(evt);
            }
        });

        btnRepSearchFind.setText("Search");
        btnRepSearchFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepSearchFindActionPerformed(evt);
            }
        });

        btnRecSearchClear.setText("Clear");

        tableRecSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RecID", "Name", "Category", "Qty", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRecSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRecSearchMouseClicked(evt);
            }
        });
        tableRecSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableRecSearchKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableRecSearch);

        jLabel19.setText("Edit / Delete Recipe");

        jLabel20.setText("Rec ID");

        txtRecEditId.setEditable(false);

        jLabel21.setText("Name");

        txtRecEditName.setEditable(false);

        jLabel22.setText("Category");

        txtRecEditCate.setEditable(false);

        radioRecDelete.setText("Delete");
        radioRecDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRecDeleteActionPerformed(evt);
            }
        });

        radioRecEdit.setText("Edit");
        radioRecEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRecEditActionPerformed(evt);
            }
        });

        btnRecEditOk.setText("OK");
        btnRecEditOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecEditOkActionPerformed(evt);
            }
        });

        tableRecIngredients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingr ID", "Name", "Category", "Qty", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRecIngredients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableRecIngredientsKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tableRecIngredients);

        jLabel23.setText("Ingredients");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecCreateClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecCreateAdd))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecCreateName)
                            .addComponent(txtRecCreateqty))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRecCreateCategory)
                            .addComponent(comboRecCreateUnit, 0, 341, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(btnRecSearchClear)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRepSearchFind))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtRepSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRecSearchCate, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRecEditOk)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtRecEditId, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRecEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(txtRecEditCate, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(704, 704, 704)
                                .addComponent(radioRecEdit)
                                .addGap(18, 18, 18)
                                .addComponent(radioRecDelete)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRecCreateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtRecCreateCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtRecCreateqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(comboRecCreateUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRecCreateAdd)
                            .addComponent(btnRecCreateClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtRepSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtRecSearchCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepSearchFind)
                    .addComponent(btnRecSearchClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtRecEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtRecEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtRecEditCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioRecDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioRecEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecEditOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRecEdit.addTab("Recipes", jPanel6);

        jLabel24.setText("Edit Recipe Details");

        jLabel25.setText("Rec ID");

        jLabel26.setText("Name");

        jLabel27.setText("Qty");

        jLabel28.setText("Unit");

        btnRecEditDetailsOk.setText("OK");
        btnRecEditDetailsOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecEditDetailsOkActionPerformed(evt);
            }
        });

        btnRecEditDetailsReset1.setText("Reset");

        jLabel29.setText("ADD Ingredients");

        jLabel30.setText("Search Ingredients");

        jLabel31.setText("Name");

        txtRecEditDetailsSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecEditDetailsSearchNameActionPerformed(evt);
            }
        });

        jLabel32.setText("Categoty");

        btnRecEditDetailsSearchFind.setText("Search");

        btnRecEditDetailsSearchClear.setText("Clear");

        jLabel33.setText("Selected Ingredients");

        tableRecEditDetailsSelectedIngre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IngreID", "Name", "Category", "Qty", "Unit", "Price(Unit)", "Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableRecEditDetailsSelectedIngre);

        jLabel34.setText("Category");

        btnRecEditDetailsSearchAddToList.setText("Add To List");
        btnRecEditDetailsSearchAddToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecEditDetailsSearchAddToListActionPerformed(evt);
            }
        });

        btnRecEditDetailsSave.setText("Save");
        btnRecEditDetailsSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecEditDetailsSaveActionPerformed(evt);
            }
        });

        btnRecEditReset2.setText("Reset");

        btnRecEditDetailsCancel.setText("Back");
        btnRecEditDetailsCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecEditDetailsCancelActionPerformed(evt);
            }
        });

        tableRecDetailsNotIncluIngre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IngreID", "Name", "Category", "Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableRecDetailsNotIncluIngre);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRecEditDetailsReset1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRecEditDetailsOk))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRecEditDetailsId)
                                            .addComponent(txtRecEditDetailsQty, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRecEditDetailsCate, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRecEditDetailsName)
                                    .addComponent(txtRecEditDetailsUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel30)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnRecEditDetailsSearchClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRecEditDetailsSearchFind))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(txtRecEditDetailsSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(txtRecEditDetailsSearchCate, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel33)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnRecEditDetailsCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecEditReset2)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecEditDetailsSave))
                    .addComponent(btnRecEditDetailsSearchAddToList, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtRecEditDetailsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtRecEditDetailsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtRecEditDetailsQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txtRecEditDetailsUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtRecEditDetailsCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRecEditDetailsOk)
                            .addComponent(btnRecEditDetailsReset1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtRecEditDetailsSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(txtRecEditDetailsSearchCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecEditDetailsSearchFind)
                    .addComponent(btnRecEditDetailsSearchClear))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnRecEditDetailsSearchAddToList)
                .addGap(4, 4, 4)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecEditDetailsSave)
                    .addComponent(btnRecEditReset2)
                    .addComponent(btnRecEditDetailsCancel))
                .addContainerGap())
        );

        panelRecEdit.addTab("Recipe Edit", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRecEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRecEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngreAddNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngreAddNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngreAddNameActionPerformed

    private void btnIngerAddCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngerAddCreateActionPerformed
        // TODO add your handling code here:
        String addName = txtIngreAddName.getText();
        String addCategory = txtIngreAddCategory.getText();

        IngredientModle im = new IngredientModle(addName, addCategory);
        //System.out.println("add boolean value: "+IngreCreateController.addIngredient(im));
        if (IngredientController.addIngredient(im)) {
            txtIngreAddName.setText("");
            txtIngreAddCategory.setText("");
            txtIngreAddName.requestFocus();
            System.out.println("success...");
            ArrayList<IngredientModle> al = IngredientController.getAllIngredients();
            addResultToIngreTable(ingreDefTablModle, al);
            String[] alertData = {"Information Dialog", "Look", "Ingredient Added Successfuly."};
            //inforMassage(alertData);
//            // get to cursor top of the table
//            int rawCount = ingreDefTablModle.getRowCount();
//            for (int i = 0; i < rawCount; i++) {
//                ingreDefTablModle.removeRow(0);
//            }
//            
//            // fill the table
//            ArrayList<IngredientModle> alim = IngreController.getAllIngredients();
//            for(int i =0 ; i < alim.size() ; i++){
//                IngredientModle imObj = alim.get(i);
//                String [] array = {imObj.getIngreID(), imObj.getIngreName(), imObj.getIngreCategory()};
//                ingreDefTablModle.addRow(array);               
//            }
        } else {
            System.out.println("fail...");
        }

    }//GEN-LAST:event_btnIngerAddCreateActionPerformed

    private boolean addResultToIngreTable(DefaultTableModel dtm, ArrayList<IngredientModle> al) {

        if (al != null) {
            int rowCount = dtm.getRowCount();
            // System.out.println("row count +++++++++++"+rowCount);
            for (int i = 0; i < rowCount; i++) {
                dtm.removeRow(0);
                //System.out.println("row count ----"+rowCount);
            }
            for (int i = 0; i < al.size(); i++) {
                IngredientModle im = al.get(i);
                Object[] array = {im.getIngreID(), im.getIngreName(), im.getIngreCategory(), false};
                dtm.addRow(array);
            }
            return true;
        }
        System.out.println("empty array...");
        //tableIngreSearch.removeRowSelectionInterval(0, 0);
        return false;
    }

    private boolean addResultToRecTable(DefaultTableModel dtm, ArrayList<RecipeModule> al) {

        if (al != null) {
//            int rowCount = dtm.getRowCount();
//            System.out.println("row count +++++++++++"+rowCount);
//            for (int i = 0; i < rowCount; i++) {
//                dtm.removeRow(0);
//                System.out.println("row count ----"+rowCount);
//            }
            dtm.setRowCount(0);

            for (int i = 0; i < al.size(); i++) {
                String[] recArray = {al.get(i).getRecID(), al.get(i).getRecName(), al.get(i).getRecCategory(), al.get(i).getRecQty(), al.get(i).getRecUnit()};
                dtm.addRow(recArray);

            }
            return true;
        }
        return false;
    }

    private boolean addResultToRecIngredientTable(DefaultTableModel dtm, ArrayList<RecIngredientsModle> ingreList) {
        if (ingreList != null) {
            int rowCount = dtm.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                dtm.removeRow(0);
            }

            for (int i = 0; i < ingreList.size(); i++) {
                String[] ingreArray = {ingreList.get(i).getIngriID(), ingreList.get(i).getIngreName(), ingreList.get(0).getIngreCategoty(), ingreList.get(i).getIngriQty(), ingreList.get(0).getIngriUnit()};
                dtm.addRow(ingreArray);

            }
            return true;
        }
        return false;
    }

    private boolean addResultToRecEditDetailsIngreTable(DefaultTableModel dtm, ArrayList<RecIngredientsModle> ingreList, int startRowCount) {
        if (ingreList != null) {

            if (startRowCount == 0) {
                int rowCount = dtm.getRowCount();
                for (int i = 0; i < rowCount; i++) {
                    dtm.removeRow(0);
                }
            }

            for (int i = 0; i < ingreList.size(); i++) {
                System.out.println("ingre list : --" + ingreList.get(i).getIngriID());
                String ingreArray[] = {ingreList.get(i).getIngriID(), ingreList.get(i).getIngreName(), ingreList.get(i).getIngreCategoty(), ingreList.get(i).getIngriQty(), ingreList.get(i).getIngriUnit(), ingreList.get(i).getIngriPrice()};
                dtm.addRow(ingreArray);
                tableRecEditDetailsSelectedIngre.setValueAt(true, i + startRowCount, 6);
            }
            return true;
        } else {
            return false;
        }
    }

    private void txtIngreEditIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngreEditIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngreEditIdActionPerformed

    private void btnIngerAddClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngerAddClearActionPerformed
        // TODO add your handling code here:
        txtIngreAddCategory.setText("");
        txtIngreAddName.setText("");
        txtIngreAddName.requestFocus();
    }//GEN-LAST:event_btnIngerAddClearActionPerformed

    private void btnIngreSearchFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreSearchFindActionPerformed
        // TODO add your handling code here

        String name = txtIngreSearchName.getText();
        String catecgory = txtIngreSearchCategory.getText();
        searchIngreName = name;
        searchIngreCategory = catecgory;
        if (name != null && catecgory != null) {
            ArrayList<IngredientModle> al = IngredientController.searchIngredients(name, catecgory);
            if (addResultToIngreTable(ingreDefTablModle, al)) {
                tableIngreSearch.requestFocus();
                tableIngreSearch.setRowSelectionInterval(0, 0);
                txtIngreEditId.setText(tableIngreSearch.getValueAt(0, 0) + "");
                txtIngreEditName.setText(tableIngreSearch.getValueAt(0, 1) + "");
                txtIngreEditCategory.setText(tableIngreSearch.getValueAt(0, 2) + "");
            } else {
                System.out.println("No Search Result found.");
                clearJTable(tableIngreSearch);
            }
        }
    }//GEN-LAST:event_btnIngreSearchFindActionPerformed

    private void btnIngreSearchClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreSearchClearActionPerformed
        txtIngreSearchName.setText("");
        txtIngreSearchCategory.setText("");
        txtIngreSearchName.requestFocus();
    }//GEN-LAST:event_btnIngreSearchClearActionPerformed

    private void tableIngreSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableIngreSearchKeyPressed
        int rowNumber = tableIngreSearch.getSelectedRow();
//        System.out.println("selected row number 01:::::" + rowNumber);
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        String name = ingreDefTablModle.getValueAt(rowNumber, 1) + "";
        String cat = ingreDefTablModle.getValueAt(rowNumber, 2) + "";
//            selectedIngreName = name;
//            selectedIngreCategory = cat;
        txtIngreEditId.setText(ingreDefTablModle.getValueAt(rowNumber, 0) + "");
        txtIngreEditName.setText(name);
        txtIngreEditCategory.setText(cat);
//            System.out.println("row index 02+++++ "+ rowNumber);
//            tableIngreSearch.setRowSelectionInterval(rowNumber, rowNumber);
//            System.out.println("row index 03----- "+ rowNumber);
//            //tableIngreSearch.setRowSelectionAllowed(false);
//        }        
    }//GEN-LAST:event_tableIngreSearchKeyPressed

    private void radioIngreEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIngreEditActionPerformed
        // TODO add your handling code here:
        System.out.println("radio delecte focus : " + radioIngreDelete.isFocusable());
        if (radioIngreEdit.isSelected() == true) {
            selectedIngreName = txtIngreEditName.getText();
            selectedIngreCategory = txtIngreEditCategory.getText();
            radioIngreDelete.setSelected(false);
            //radioIngreDelete.setEnabled(false);
            txtIngreEditName.setEnabled(true);
            txtIngreEditCategory.setEnabled(true);
            txtIngreEditName.setEditable(true);
            txtIngreEditCategory.setEditable(true);
            btnIngreEditSetDefult.setEnabled(true);
            btnIngreEditOk.setEnabled(true);
        }
        if (radioIngreEdit.isSelected() == false) {
            txtIngreEditName.setText(selectedIngreName);
            txtIngreEditCategory.setText(selectedIngreCategory);
            btnIngreEditOk.setEnabled(false);
            btnIngreEditSetDefult.setEnabled(false);
            radioIngreDelete.setEnabled(true);
            txtIngreEditName.setEnabled(false);
            txtIngreEditId.setEnabled(false);
            txtIngreEditCategory.setEnabled(false);
        }
        System.out.println("radio button status : " + radioIngreEdit.isSelected());
    }//GEN-LAST:event_radioIngreEditActionPerformed

    private void radioIngreDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIngreDeleteActionPerformed
        if (radioIngreDelete.isSelected() == true) {
            radioIngreEdit.setSelected(false);
            if (selectedIngreName != null && selectedIngreCategory != null) {
                txtIngreEditName.setText(selectedIngreName);
                txtIngreEditCategory.setText(selectedIngreCategory);
            }
            btnIngreEditSetDefult.setEnabled(false);
            btnIngreEditOk.setEnabled(true);
            txtIngreEditName.setEnabled(false);
            txtIngreEditCategory.setEnabled(false);
        } else {
            btnIngreEditOk.setEnabled(false);
        }
    }//GEN-LAST:event_radioIngreDeleteActionPerformed

    private void tableIngreSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableIngreSearchKeyReleased
        int rowNumber = tableIngreSearch.getSelectedRow();
        // TODO
        //if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        String name = ingreDefTablModle.getValueAt(rowNumber, 1) + "";
        String cat = ingreDefTablModle.getValueAt(rowNumber, 2) + "";
        selectedIngreName = name;
        selectedIngreCategory = cat;
        txtIngreEditId.setText(ingreDefTablModle.getValueAt(rowNumber, 0) + "");
        txtIngreEditName.setText(name);
        txtIngreEditCategory.setText(cat);
        //}

    }//GEN-LAST:event_tableIngreSearchKeyReleased


    private void btnIngreEditSetDefultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreEditSetDefultActionPerformed

        txtIngreEditName.setText(selectedIngreName);
        txtIngreEditCategory.setText(selectedIngreCategory);
        txtIngreEditName.requestFocus();
    }//GEN-LAST:event_btnIngreEditSetDefultActionPerformed

    private void btnIngreEditOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreEditOkActionPerformed
        // TODO add your handling code here:
        int rowID = tableIngreSearch.getSelectedRow();
        System.out.println("row : " + rowID);
        if (radioIngreEdit.isSelected()) {
            IngredientModle im = new IngredientModle(txtIngreEditId.getText(), txtIngreEditName.getText(), txtIngreEditCategory.getText());
            if (IngredientController.updateIngredient(im)) {
                System.out.println("Successfully Update.");
                searchIngreName = "";
                searchIngreCategory = "";
                ArrayList<IngredientModle> al = IngredientController.searchIngredients(searchIngreName, searchIngreCategory);
                if (addResultToIngreTable(ingreDefTablModle, al)) {
                    tableIngreSearch.requestFocus();
                    tableIngreSearch.setRowSelectionInterval(0, 0);
                    txtIngreEditId.setText(tableIngreSearch.getValueAt(0, 0) + "");
                    txtIngreEditName.setText(tableIngreSearch.getValueAt(0, 1) + "");
                    txtIngreEditCategory.setText(tableIngreSearch.getValueAt(0, 2) + "");
                } else {
                    System.out.println("Empty Data.");
                    tableIngreSearch.removeRowSelectionInterval(0, 0);
                    clearJTable(tableIngreSearch);
                    txtIngreEditId.setText("");
                    txtIngreEditName.setText("");
                    txtIngreEditCategory.setText("");
                }
            }
        }
        if (radioIngreDelete.isSelected()) {
            if (IngredientController.removeIngredient(txtIngreEditId.getText())) {
                if (searchIngreName == null && searchIngreCategory == null) {
                    searchIngreName = "";
                    searchIngreCategory = "";
                }
                if (addResultToIngreTable(ingreDefTablModle, IngredientController.searchIngredients(searchIngreName, searchIngreCategory))) {
                    if (tableIngreSearch.getRowCount() > 0) {
                        if (rowID == 0) {
                            tableIngreSearch.setRowSelectionInterval(rowID, rowID);
                            txtIngreEditId.setText(tableIngreSearch.getValueAt(rowID, 0) + "");
                            txtIngreEditName.setText(tableIngreSearch.getValueAt(rowID, 1) + "");
                            txtIngreEditCategory.setText(tableIngreSearch.getValueAt(rowID, 2) + "");
                        } else if (rowID == tableIngreSearch.getRowCount()) {
                            tableIngreSearch.setRowSelectionInterval(rowID - 1, rowID - 1);
                            txtIngreEditId.setText(tableIngreSearch.getValueAt(rowID - 1, 0) + "");
                            txtIngreEditName.setText(tableIngreSearch.getValueAt(rowID - 1, 1) + "");
                            txtIngreEditCategory.setText(tableIngreSearch.getValueAt(rowID - 1, 2) + "");
                        } else {
                            tableIngreSearch.setRowSelectionInterval(rowID, rowID);
                            txtIngreEditId.setText(tableIngreSearch.getValueAt(rowID, 0) + "");
                            txtIngreEditName.setText(tableIngreSearch.getValueAt(rowID, 1) + "");
                            txtIngreEditCategory.setText(tableIngreSearch.getValueAt(rowID, 2) + "");
                        }
                    } else {
                        txtIngreEditId.setText("");
                        txtIngreEditName.setText("");
                        txtIngreEditCategory.setText("");
                    }
                } else {
                    System.out.println("Empty Result.");
                    txtIngreEditId.setText("");
                    txtIngreEditName.setText("");
                    txtIngreEditCategory.setText("");
                    tableIngreSearch.removeRowSelectionInterval(0, 0);
                    clearJTable(tableIngreSearch);
                }
            } else {
                System.out.println("Fail Delete ingredient.");
            }

        }
    }//GEN-LAST:event_btnIngreEditOkActionPerformed

    private void txtRecCreateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecCreateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecCreateNameActionPerformed

    private void txtRecSearchCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecSearchCateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecSearchCateActionPerformed

    private void btnRepSearchFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepSearchFindActionPerformed

        ArrayList<RecipeModule> al = RecipeController.searchRecipes(txtRepSearchName.getText(), txtRecSearchCate.getText());
        if (addResultToRecTable(recDefaultTableModel, al)) {
            //           if (addResultToRecTable(recIngredientsTableModle, al)) {
            tableRecSearch.requestFocus();
            tableRecSearch.setRowSelectionInterval(0, 0);
            txtRecEditId.setText(tableRecSearch.getValueAt(0, 0) + "");
            txtRecEditName.setText(tableRecSearch.getValueAt(0, 1) + "");
            txtRecEditCate.setText(tableRecSearch.getValueAt(0, 2) + "");

            recIngreList = RecIngredientsController.getRecipeIngredients(txtRecEditId.getText());
//            if(addResultToRecIngredientTable(recIngredientsTableModle, recIngreList)){
//        ArrayList<RecIngredientsModle> recIngreList = RecIngredientsController.getRecipeIngredients("REC01");
            if (addResultToRecIngredientTable(recIngredientsTableModle, recIngreList)) {
                System.out.println("Completly ADD Ingredients to Table...");
            } else {
                // clearJTable(tableRecIngredients);
                System.out.println("Empty Data.");
            }
        } else {
            clearJTable(tableIngreSearch);
        }
    }//GEN-LAST:event_btnRepSearchFindActionPerformed

    private void radioRecDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRecDeleteActionPerformed
        // TODO add your handling code here:
        if (radioRecDelete.isSelected()) {
            radioRecEdit.setSelected(false);
        }
    }//GEN-LAST:event_radioRecDeleteActionPerformed

    private void radioRecEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRecEditActionPerformed
        // TODO add your handling code here:
        if (radioRecEdit.isSelected()) {
            radioRecDelete.setSelected(false);
        }
    }//GEN-LAST:event_radioRecEditActionPerformed

    private void btnRecEditOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecEditOkActionPerformed
        // TODO add your handling code here:
        if (radioRecEdit.isSelected()) {
            int seleRow = tableRecSearch.getSelectedRow();
            txtRecEditDetailsId.setText(tableRecSearch.getValueAt(seleRow, 0) + "");
            txtRecEditDetailsName.setText(tableRecSearch.getValueAt(seleRow, 1) + "");
            txtRecEditDetailsQty.setText(tableRecSearch.getValueAt(seleRow, 3) + "");
            txtRecEditDetailsUnit.setText(tableRecSearch.getValueAt(seleRow, 4) + "");
            txtRecEditDetailsCate.setText(tableRecSearch.getValueAt(seleRow, 2) + "");
            panelRecEdit.setSelectedIndex(2);

            if (addResultToRecEditDetailsIngreTable(recDetailsEditIngreModle, recIngreList, 0)) {
                System.out.println("Add Incuded Ingredienys Successfuly...");
            } else {
                clearJTable(tableRecEditDetailsSelectedIngre);
            }

            ArrayList<IngredientModle> ingreArray = RecIngredientsController.getNotIncludedIngredientsInRec(tableRecSearch.getValueAt(seleRow, 0) + "");
            if (addResultToIngreTable(recDetailsEditNotIncluModle, ingreArray)) {
                System.out.println("Add Not Incuded Ingredienys Successfuly...");
            } else {
                clearJTable(tableRecDetailsNotIncluIngre);
                System.out.println("Add Not Incuded Ingredienys Fails...");
            }
        }
    }//GEN-LAST:event_btnRecEditOkActionPerformed

    private void btnRecEditDetailsOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecEditDetailsOkActionPerformed
        // TODO add your handling code here:
        RecipeModule rm = new RecipeModule(txtRecEditDetailsId.getText(), txtRecEditDetailsName.getText(), txtRecEditDetailsCate.getText(), txtRecEditDetailsQty.getText(), txtRecEditDetailsUnit.getText());
        RecIngredientsController.updateRecDetails(rm);
    }//GEN-LAST:event_btnRecEditDetailsOkActionPerformed

    private void txtRecEditDetailsSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecEditDetailsSearchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecEditDetailsSearchNameActionPerformed

    private void btnRecCreateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecCreateAddActionPerformed
        RecipeModule rm = new RecipeModule(txtRecCreateName.getText(), txtRecCreateCategory.getText(), txtRecCreateqty.getText(), comboRecCreateUnit.getSelectedItem().toString());
        if (RecipeController.addRecipe(rm)) {
            System.out.println("Successfully Create Recipe...");
            txtRecCreateName.setText("");
            txtRecCreateCategory.setText("");
            txtRecCreateqty.setText("");
            comboRecCreateUnit.setSelectedIndex(0);
        } else {
            System.out.println("Create Recipe Fail...");
        }
        //System.out.println("selected val :"+ comboRecCreateUnit.getSelectedItem().toString());
    }//GEN-LAST:event_btnRecCreateAddActionPerformed

    private void btnRecCreateClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecCreateClearActionPerformed
        txtRecCreateName.setText("");
        txtRecCreateCategory.setText("");
        txtRecCreateqty.setText("");
        comboRecCreateUnit.setSelectedIndex(0);
    }//GEN-LAST:event_btnRecCreateClearActionPerformed

    private void tableRecSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableRecSearchKeyReleased
        try {
            clearJTable(tableRecIngredients);
            System.out.println(tableRecSearch.getSelectedRow());
            int selectedRow = tableRecSearch.getSelectedRow();
////        System.out.println("0000000000 :" +selectedRow);
////        System.out.println("row count ================="+tableRecSearch.getRowCount());
            txtRecEditId.setText(tableRecSearch.getValueAt(selectedRow, 0) + "");
//        System.out.println("111111111");
            txtRecEditName.setText(tableRecSearch.getValueAt(selectedRow, 1) + "");
            txtRecEditCate.setText(tableRecSearch.getValueAt(selectedRow, 2) + "");
//            System.out.println("0, 1, 2 :-"+tableRecSearch.getValueAt(selectedRow, 0) + "  "+tableRecSearch.getValueAt(selectedRow, 2) + "");
//            System.out.println("txtRecEditId.getText() " + txtRecEditId.getText());
            //recIngreList.clear();
            recIngreList = RecIngredientsController.getRecipeIngredients(txtRecEditId.getText());
//            clearJTable(tableRecIngredients);
            
            if (recIngreList != null) {
                System.out.println("+++++++++++++++++++");
                
                System.out.println("--------------- 01");
                if (addResultToRecIngredientTable(recIngredientsTableModle, recIngreList)) {
                    System.out.println(""
                            + "Completly ADD Ingredients to Table...");
                    System.out.println("--------------- 02");
                } else {
                    System.out.println("--------------- 03");
                    recIngreList.clear();
                    clearJTable(tableRecIngredients);
                    DefaultTableModel dtm = recIngredientsTableModle;
                            dtm.setRowCount(0);
                    System.out.println("Empty Data.");
                }

            }else {
                System.out.println("--------------- 04");
                //recIngreList.clear();
                DefaultTableModel dtm = recIngredientsTableModle;
                            dtm.setRowCount(0);
                //clearJTable(tableRecIngredients);
            }

        } catch (Exception e) {
            System.out.println("Exception :++++" + e);
        }
    }//GEN-LAST:event_tableRecSearchKeyReleased

    private void tableRecSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRecSearchMouseClicked
        // TODO add your handling code here:

        System.out.println(tableRecSearch.getSelectedRow());
    }//GEN-LAST:event_tableRecSearchMouseClicked

    private void tableRecIngredientsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableRecIngredientsKeyPressed
        // TODO add your handling code here:
        System.out.println(tableRecIngredients.getSelectedRow());
    }//GEN-LAST:event_tableRecIngredientsKeyPressed
///.....................................................................


    private void btnRecEditDetailsSearchAddToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecEditDetailsSearchAddToListActionPerformed

        ArrayList<RecIngredientsModle> selectedIngreList = getSelectedDataFromTable(tableRecDetailsNotIncluIngre);
        int startRowCount = tableRecEditDetailsSelectedIngre.getRowCount();
        if (addResultToRecEditDetailsIngreTable(recDetailsEditIngreModle, selectedIngreList, startRowCount)) {
            System.out.println("Add Incuded Ingredienys Successfuly...");
        }
    }//GEN-LAST:event_btnRecEditDetailsSearchAddToListActionPerformed

    private void btnRecEditDetailsSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecEditDetailsSaveActionPerformed
        //
        ///''''''''''''''''''''''''' 
        ArrayList<RecIngredientsModle> saveIngreList = getSelectedDataFromTable(tableRecEditDetailsSelectedIngre);
        boolean result = RecIngredientsController.updateRecIngreDetails(saveIngreList, txtRecEditDetailsId.getText());
        System.out.println("final result:" + result);
    }//GEN-LAST:event_btnRecEditDetailsSaveActionPerformed

    private void btnRecEditDetailsCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecEditDetailsCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecEditDetailsCancelActionPerformed

    private ArrayList<RecIngredientsModle> getSelectedDataFromTable(JTable table) {
        ArrayList<RecIngredientsModle> list = new ArrayList<>();
        RecIngredientsModle mod = new RecIngredientsModle();
        for (int i = 0; i < table.getRowCount(); i++) {

            if (table.equals(tableRecDetailsNotIncluIngre)) {
                System.out.println("true : tableRecDetailsNotIncluIngre");

                String boolValue = table.getValueAt(i, 3).toString();

                if ("true".equals(boolValue)) {
                    mod.setIngriID(table.getValueAt(i, 0).toString());
                    mod.setIngreName(table.getValueAt(i, 1).toString());
                    mod.setIngreCategoty(table.getValueAt(i, 2).toString());
                    list.add(mod);
                    ((DefaultTableModel) table.getModel()).removeRow(i);
                }
            } else if (table.equals(tableRecEditDetailsSelectedIngre)) {
                System.out.println("true: tableRecDetailsIncluIngre");
                String boolValue = table.getValueAt(i, 6).toString();
                System.out.println("+++++++++++++++++++" + table.getValueAt(i, 5).toString());
                if ("true".equals(boolValue)) {
                    mod.setIngriID(table.getValueAt(i, 0).toString());
                    mod.setIngreName(table.getValueAt(i, 1).toString());
                    mod.setIngreCategoty(table.getValueAt(i, 2).toString());
                    System.out.println("+++++++++++++++++++" + table.getValueAt(i, 4).toString());
                    mod.setIngriQty(table.getValueAt(i, 3).toString());
                    mod.setIngriUnit(table.getValueAt(i, 4).toString());
                    mod.setIngriPrice(table.getValueAt(i, 5).toString());
                    list.add(mod);
                }
            }
        }
        return list;
    }

    // clear the jtable content
    private void clearJTable(final JTable table) {
        for (int i = 0; i < table.getRowCount(); i++) {
            for (int j = 0; j < table.getColumnCount(); j++) {
                table.setValueAt(null, i, j);
            }
        }
    }

    // information message
    private void inforMassage(String[] alertData) {
//        Alert alert = new Alert(AlertType.INFORMATION);
//        alert.setTitle(alertData[0]);
//        alert.setHeaderText(alertData[1]);
//        alert.setContentText(alertData[2]);
//        alert.show();
        try {
            System.out.println("01");
            Alert alert = new Alert(AlertType.INFORMATION);
            System.out.println("02");
            alert.setTitle("Information Dialog");
            alert.setHeaderText(null);
            alert.setContentText("I have a great message for you!");
            System.out.println("03");
            alert.showAndWait();
            System.out.println("04");
        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngerAddClear;
    private javax.swing.JButton btnIngerAddCreate;
    private javax.swing.JButton btnIngreEditOk;
    private javax.swing.JButton btnIngreEditSetDefult;
    private javax.swing.JButton btnIngreSearchClear;
    private javax.swing.JButton btnIngreSearchFind;
    private javax.swing.JButton btnRecCreateAdd;
    private javax.swing.JButton btnRecCreateClear;
    private javax.swing.JButton btnRecEditDetailsCancel;
    private javax.swing.JButton btnRecEditDetailsOk;
    private javax.swing.JButton btnRecEditDetailsReset1;
    private javax.swing.JButton btnRecEditDetailsSave;
    private javax.swing.JButton btnRecEditDetailsSearchAddToList;
    private javax.swing.JButton btnRecEditDetailsSearchClear;
    private javax.swing.JButton btnRecEditDetailsSearchFind;
    private javax.swing.JButton btnRecEditOk;
    private javax.swing.JButton btnRecEditReset2;
    private javax.swing.JButton btnRecSearchClear;
    private javax.swing.JButton btnRepSearchFind;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox comboRecCreateUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane panelRecEdit;
    private javax.swing.JRadioButton radioIngreDelete;
    private javax.swing.JRadioButton radioIngreEdit;
    private javax.swing.JRadioButton radioRecDelete;
    private javax.swing.JRadioButton radioRecEdit;
    private javax.swing.JTable tableIngreSearch;
    private javax.swing.JTable tableRecDetailsNotIncluIngre;
    private javax.swing.JTable tableRecEditDetailsSelectedIngre;
    private javax.swing.JTable tableRecIngredients;
    private javax.swing.JTable tableRecSearch;
    private javax.swing.JTextField txtIngreAddCategory;
    private javax.swing.JTextField txtIngreAddName;
    private javax.swing.JTextField txtIngreEditCategory;
    private javax.swing.JTextField txtIngreEditId;
    private javax.swing.JTextField txtIngreEditName;
    private javax.swing.JTextField txtIngreSearchCategory;
    private javax.swing.JTextField txtIngreSearchName;
    private javax.swing.JTextField txtRecCreateCategory;
    private javax.swing.JTextField txtRecCreateName;
    private javax.swing.JTextField txtRecCreateqty;
    private javax.swing.JTextField txtRecEditCate;
    private javax.swing.JTextField txtRecEditDetailsCate;
    private javax.swing.JTextField txtRecEditDetailsId;
    private javax.swing.JTextField txtRecEditDetailsName;
    private javax.swing.JTextField txtRecEditDetailsQty;
    private javax.swing.JTextField txtRecEditDetailsSearchCate;
    private javax.swing.JTextField txtRecEditDetailsSearchName;
    private javax.swing.JTextField txtRecEditDetailsUnit;
    private javax.swing.JTextField txtRecEditId;
    private javax.swing.JTextField txtRecEditName;
    private javax.swing.JTextField txtRecSearchCate;
    private javax.swing.JTextField txtRepSearchName;
    // End of variables declaration//GEN-END:variables
}
